"""empty message

Revision ID: 6ee74c9699d0
Revises: afcddb178576
Create Date: 2024-02-18 06:11:14.247428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6ee74c9699d0'
down_revision: Union[str, None] = 'afcddb178576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_scholarly_review')
    op.drop_table('data_final_lit_review')
    op.drop_table('data_relevant_articles')
    op.drop_table('data_new_research')
    op.drop_table('data_paul_graham_essay')
    op.drop_table('data_literature_review')
    op.drop_table('data_previous_research')
    op.drop_table('data_cs_ethics')
    op.drop_table('data_ed_resources')
    op.drop_table('data_current_research')
    op.drop_table('data_education_research')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_education_research',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.Oq4X.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_EDUCATION_RESEAPKey3')
    )
    op.create_table('data_current_research',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.CbvZ.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_CURRENT_RESEARCPKey3')
    )
    op.create_table('data_ed_resources',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.B0Ye.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_ED_RESOURCESPKey3')
    )
    op.create_table('data_cs_ethics',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.Crra.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_CS_ETHICSPKey3')
    )
    op.create_table('data_previous_research',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.Tt3l.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_PREVIOUS_RESEARPKey3')
    )
    op.create_table('data_literature_review',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.BPax.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_LITERATURE_REVIPKey3')
    )
    op.create_table('data_paul_graham_essay',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.B73v.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_PAUL_GRAHAM_ESSPKey3')
    )
    op.create_table('data_new_research',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.BY4i.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_NEW_RESEARCHPKey3')
    )
    op.create_table('data_relevant_articles',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.Cpt6.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_RELEVANT_ARTICLPKey3')
    )
    op.create_table('data_final_lit_review',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.BOkR.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_FINAL_LIT_REVIEPKey3')
    )
    op.create_table('data_scholarly_review',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('$i(^poCN.DKMZ.1)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=65535), autoincrement=False, nullable=False),
    sa.Column('metadata_', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('partition_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DATA_SCHOLARLY_REVIEPKey3')
    )
    # ### end Alembic commands ###
